
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: istio-cluster01cluster02gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster01cluster02gateway
    istio.io/rev: istio-system-cluster02
    operator.istio.io/component: IngressGateways
    release: istio
    topology.istio.io/network: network2
  name: istio-cluster01cluster02gateway-service-account
  namespace: istio-system-cluster02

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istio-cluster01cluster02gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster01cluster02gateway
    istio.io/rev: istio-system-cluster02
    operator.istio.io/component: IngressGateways
    release: istio
    topology.istio.io/network: network2
  name: istio-cluster01cluster02gateway
  namespace: istio-system-cluster02
spec:
  selector:
    matchLabels:
      app: istio-cluster01cluster02gateway
      istio: cluster01cluster02gateway
      topology.istio.io/network: network2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      annotations:
        inject.istio.io/templates: gateway
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
        sidecar.istio.io/inject: "true"
      labels:
        app: istio-cluster01cluster02gateway
        chart: gateways
        heritage: Tiller
        install.operator.istio.io/owning-resource: unknown
        istio: cluster01cluster02gateway
        operator.istio.io/component: IngressGateways
        release: istio
        sidecar.istio.io/inject: "true"
        topology.istio.io/network: network2
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution: null
          requiredDuringSchedulingIgnoredDuringExecution: null
      containers:
        - env:
            - name: ISTIO_META_REQUESTED_NETWORK_VIEW
              value: network2
            - name: ISTIO_META_UNPRIVILEGED_POD
              value: "true"
          image: auto
          name: istio-proxy
          ports:
            - containerPort: 15021
              protocol: TCP
            - containerPort: 15443
              protocol: TCP
            - containerPort: 15012
              protocol: TCP
            - containerPort: 15017
              protocol: TCP
            - containerPort: 15090
              name: http-envoy-prom
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /etc/istio/ingressgateway-certs
              name: ingressgateway-certs
              readOnly: true
            - mountPath: /etc/istio/ingressgateway-ca-certs
              name: ingressgateway-ca-certs
              readOnly: true
      serviceAccountName: istio-cluster01cluster02gateway-service-account
      volumes:
        - name: ingressgateway-certs
          secret:
            optional: true
            secretName: istio-ingressgateway-certs
        - name: ingressgateway-ca-certs
          secret:
            optional: true
            secretName: istio-ingressgateway-ca-certs

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: istio-cluster01cluster02gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster01cluster02gateway
    istio.io/rev: istio-system-cluster02
    operator.istio.io/component: IngressGateways
    release: istio
    topology.istio.io/network: network2
  name: istio-cluster01cluster02gateway
  namespace: istio-system-cluster02
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-cluster01cluster02gateway
      istio: cluster01cluster02gateway
      topology.istio.io/network: network2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: istio-system-cluster02
    operator.istio.io/component: IngressGateways
    release: istio
  name: istio-cluster01cluster02gateway-sds
  namespace: istio-system-cluster02
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    install.operator.istio.io/owning-resource: unknown
    istio.io/rev: istio-system-cluster02
    operator.istio.io/component: IngressGateways
    release: istio
  name: istio-cluster01cluster02gateway-sds
  namespace: istio-system-cluster02
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-cluster01cluster02gateway-sds
subjects:
  - kind: ServiceAccount
    name: istio-cluster01cluster02gateway-service-account

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: istio-cluster01cluster02gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster01cluster02gateway
    istio.io/rev: istio-system-cluster02
    operator.istio.io/component: IngressGateways
    release: istio
    topology.istio.io/network: network2
  name: istio-cluster01cluster02gateway
  namespace: istio-system-cluster02
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-cluster01cluster02gateway

---
apiVersion: v1
kind: Service
metadata:
  annotations: null
  labels:
    app: istio-cluster01cluster02gateway
    install.operator.istio.io/owning-resource: unknown
    istio: cluster01cluster02gateway
    istio.io/rev: istio-system-cluster02
    operator.istio.io/component: IngressGateways
    release: istio
    topology.istio.io/network: network2
  name: istio-cluster01cluster02gateway
  namespace: istio-system-cluster02
spec:
  ports:
    - name: status-port
      port: 15021
      protocol: TCP
      targetPort: 15021
    - name: tls
      port: 15443
      protocol: TCP
      targetPort: 15443
    - name: tls-istiod
      port: 15012
      protocol: TCP
      targetPort: 15012
    - name: tls-webhook
      port: 15017
      protocol: TCP
      targetPort: 15017
  selector:
    app: istio-cluster01cluster02gateway
    istio: cluster01cluster02gateway
    topology.istio.io/network: network2
  type: LoadBalancer

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cross-network-gateway
  namespace: istio-system-cluster02
spec:
  selector:
    istio: cluster01cluster02gateway
  servers:
    - port:
        number: 15443
        name: tls
        protocol: TLS
      tls:
        mode: AUTO_PASSTHROUGH
      hosts:
        - "*.local"